force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Kandidat</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kandidater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_on_list__c/Candidate_on_list__c.object-meta.xml
<CustomObject>
    <label>Kandidat op liste</label>
    <nameField>
        <label>Candidate on list Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kandidat på lister</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_on_list__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipName>Candidate_on_list</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/fields/Candidatelistnumber__c.field-meta.xml
<CustomField>
    <fullName>Candidatelistnumber__c</fullName>
    <externalId>true</externalId>
    <label>Candidatelistnumber</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/fields/Copy_of_notes__c.field-meta.xml
<CustomField>
    <fullName>Copy_of_notes__c</fullName>
    <label>Copy of notes</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/TAG_GeneratePdfController.cls
public class TAG_GeneratePdfController {
    private ApexPages.StandardController standardController;

    public TAG_GeneratePdfController(ApexPages.StandardController controller) {
        this.standardController = controller;
    }

    public List<Candidate_on_list__c> getCandidateOnList() {
        List<Candidate_on_list__c> records = [
            SELECT Name, Candidatelistnumber__c, Copy_of_notes__c
            FROM Candidate_on_list__c
            WHERE Candidate__c = :ApexPages.currentPage().getParameters().get('id')
        ];

        return records;
    }
}