force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Kandidat</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kandidater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Candidate_number__c.field-meta.xml
<CustomField>
    <fullName>Candidate_number__c</fullName>
    <externalId>true</externalId>
    <label>Candidate number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Personnumber__c.field-meta.xml
<CustomField>
    <fullName>Personnumber__c</fullName>
    <externalId>true</externalId>
    <label>Personnumber</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/Candidate_on_list__c.object-meta.xml
<CustomObject>
    <label>Kandidat op liste</label>
    <nameField>
        <label>Candidate on list Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kandidat på lister</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_on_list__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipName>Candidate_on_list</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/fields/List__c.field-meta.xml
<CustomField>
    <fullName>List__c</fullName>
    <label>List</label>
    <referenceTo>List__c</referenceTo>
    <relationshipLabel>Candidate on list</relationshipLabel>
    <relationshipName>Candidate_on_list</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <label>Liste</label>
    <nameField>
        <label>List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lister</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/event-monitoring/classes/UriEventService_PoagInnsyn_Test.cls
@IsTest
private class UriEventService_PoagInnsyn_Test{

    @IsTest
    private static void addPersonRelatedRecordsToLog_forCandidates() {
        //check test data
        List<Candidate__c> candidates=new List<Candidate__c>{
            new Candidate__c(Candidate_number__c='1', Name='First', Personnumber__c='1234'),
            new Candidate__c(Candidate_number__c='2', Name='Second')
        };
        insert candidates;
        System.assertEquals(2, candidates.size());

        //create test uriEvents
        List<UriEvent> uriEvents = new List<UriEvent>();
        uriEvents.add(new UriEvent(candidates[0].Id, DateTime.now(), 'Candidate__c', 'Read', 'user@user.nav.no', 'Standard'));
        uriEvents.add(new UriEvent(candidates[1].Id, DateTime.now(), 'Candidate__c', 'Read', 'user@user.nav.no', 'Standard'));

        Test.startTest();
        UriEventService_PoagInnsyn.addPersonRelatedRecordsToLog(uriEvents);
        Test.stopTest();

        List<Log__c> logs = [SELECT CRM_PersonIdent__c FROM Log__c WHERE CRM_Type__c = 'LightningUriEvent'];
        System.assertEquals(1, logs.size(), 'One log element is created');
        System.assertEquals(
            candidates[0].Personnumber__c,
            logs[0].CRM_PersonIdent__c,
            'Log element should have persons fødselsr'
        );
    }

    @IsTest
    private static void addPersonRelatedRecordsToLog_forCandidatesOnList() {
        //check test data
        List<Candidate__c> candidates=new List<Candidate__c>{
            new Candidate__c(Candidate_number__c='1', Name='First', Personnumber__c='1234'),
            new Candidate__c(Candidate_number__c='2', Name='Second')
        };
        insert candidates;

        List__c candidateList= new List__c(Name='List');
        insert candidateList;
        
        List<Candidate_on_list__c> candidateOnLists=new List<Candidate_on_list__c>{
            new Candidate_on_list__c(Candidate__c=candidates[0].Id, List__c=candidateList.Id),
            new Candidate_on_list__c(Candidate__c=candidates[1].Id, List__c=candidateList.Id)
        };
        insert candidateOnLists;

        System.assertEquals(2, candidateOnLists.size());

        //create test uriEvents
        List<UriEvent> uriEvents = new List<UriEvent>();
        uriEvents.add(new UriEvent(candidateOnLists[0].Id, DateTime.now(), 'Candidate_on_list__c', 'Read', 'user@user.nav.no', 'Standard'));
        uriEvents.add(new UriEvent(candidateOnLists[1].Id, DateTime.now(), 'Candidate_on_list__c', 'Read', 'user@user.nav.no', 'Standard'));

        Test.startTest();
        UriEventService_PoagInnsyn.addPersonRelatedRecordsToLog(uriEvents);
        Test.stopTest();

        List<Log__c> logs = [SELECT CRM_PersonIdent__c FROM Log__c WHERE CRM_Type__c = 'LightningUriEvent'];
        System.assertEquals(1, logs.size(), 'One log element is created');
        System.assertEquals(
            candidates[0].Personnumber__c,
            logs[0].CRM_PersonIdent__c,
            'Log element should have persons fødselsr'
        );
    }

 
}