force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Kandidat</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kandidater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Candidate_number__c.field-meta.xml
<CustomField>
    <fullName>Candidate_number__c</fullName>
    <externalId>true</externalId>
    <label>Candidate number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Personnumber__c.field-meta.xml
<CustomField>
    <fullName>Personnumber__c</fullName>
    <externalId>true</externalId>
    <label>Personnumber</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_Comment_on_list__c/Candidate_Comment_on_list__c.object-meta.xml
<CustomObject>
    <label>Candidate Comment on list</label>
    <nameField>
        <label>Candidate Comment on list Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Comment on lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Comment_on_list__c/fields/Date_added_to_list__c.field-meta.xml
<CustomField>
    <fullName>Date_added_to_list__c</fullName>
    <label>Date added to list</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Comment_on_list__c/fields/Kandidat_p_liste__c.field-meta.xml
<CustomField>
    <fullName>Kandidat_p_liste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kandidat på liste</label>
    <referenceTo>Candidate_on_list__c</referenceTo>
    <relationshipLabel>Candidate Comment on lists</relationshipLabel>
    <relationshipName>Candidate_Comment_on_lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/Candidate_on_list__c.object-meta.xml
<CustomObject>
    <label>Kandidat op liste</label>
    <nameField>
        <label>Candidate on list Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kandidat på lister</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_on_list__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipName>Candidate_on_list</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/fields/Candidatelistnumber__c.field-meta.xml
<CustomField>
    <fullName>Candidatelistnumber__c</fullName>
    <externalId>true</externalId>
    <label>Candidatelistnumber</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/fields/Date_added_to_list__c.field-meta.xml
<CustomField>
    <fullName>Date_added_to_list__c</fullName>
    <label>Date added to list</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_on_list__c/fields/List__c.field-meta.xml
<CustomField>
    <fullName>List__c</fullName>
    <label>List</label>
    <referenceTo>List__c</referenceTo>
    <relationshipLabel>Candidate on list</relationshipLabel>
    <relationshipName>Candidate_on_list</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <label>Liste</label>
    <nameField>
        <label>List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lister</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List__c/fields/List_description__c.field-meta.xml
<CustomField>
    <fullName>List_description__c</fullName>
    <label>List description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/List__c/fields/List_Name__c.field-meta.xml
<CustomField>
    <fullName>List_Name__c</fullName>
    <label>List Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List__c/fields/Listnumk__c.field-meta.xml
<CustomField>
    <fullName>Listnumk__c</fullName>
    <externalId>true</externalId>
    <label>Listenummerid</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TAG_GeneratePdfControllerTest.cls
@IsTest
public with sharing class TAG_GeneratePdfControllerTest {
    @TestSetup
    static void makeData() {
        Candidate__c candidate1 = new Candidate__c(
            Name = '1527367521',
            Candidate_number__c = '2378457832',
            Personnumber__c = '12345678987'
        );
        insert candidate1;

        List__c list1 = new List__c(
            Name = '2387648932',
            List_Name__c = 'NAV liste',
            List_description__c = 'Manchester United ledet både 2–0 og 3–1 og så ut til å ha full kontroll borte mot Wolverhampton.',
            Listnumk__c = '8732894723894'
        );
        insert list1;

        List__c list2 = new List__c(
            Name = '2387648888',
            List_Name__c = 'UIO liste',
            List_description__c = 'skrev seg inn i alle Manchester United-supporteres hjerter torsdag kveld. Nå holdes det ikke tilbake på superlativene om stjerneskuddet.',
            Listnumk__c = '8732894723888'
        );
        insert list2;
    }

    @IsTest
    static void testGeneratePdfControllerPositive() {
        Candidate__c candidate = [SELECT Id FROM Candidate__c WHERE Name = '1527367521'];

        List<List__c> listNAV = [SELECT Id FROM List__c WHERE Name = '2387648932'];

        List<List__c> listUIO = [SELECT Id FROM List__c WHERE Name = '2387648888'];

        Candidate_on_list__c candidateOnListNAV = new Candidate_on_list__c(
            Candidate__c = candidate.Id,
            Name = '6238238',
            Candidatelistnumber__c = '328947389',
            List__c = listNAV[0].Id
        );
        insert candidateOnListNAV;

        Candidate_on_list__c candidateOnListUIO = new Candidate_on_list__c(
            Candidate__c = candidate.Id,
            Name = '6238267',
            Candidatelistnumber__c = '328947355',
            List__c = listUIO[0].Id
        );
        insert candidateOnListUIO;

        Candidate_Comment_on_list__c commentOnListNAV1 = new Candidate_Comment_on_list__c(
            Kandidat_p_liste__c = candidateOnListNAV.Id,
            Name = '63722154125',
            Comment__c = 'Following losses to Nottingham Forest and Manchester City, the black and whites are bidding to avoid a trio of successive PL home defeats for the first time since January/February 2021.',
            Date_added_to_list__c = Date.TODAY()
        );
        insert commentOnListNAV1;

        Candidate_Comment_on_list__c commentOnListNAV2 = new Candidate_Comment_on_list__c(
            Kandidat_p_liste__c = candidateOnListNAV.Id,
            Name = '6372215333',
            Comment__c = 'Following losses to Nottingham Forest and Manchester City, the black and whites are bidding to avoid a trio of successive PL home defeats for the first time since January/February 2021.',
            Date_added_to_list__c = Date.TODAY()
        );
        insert commentOnListNAV2;

        Candidate_Comment_on_list__c commentOnListUIO1 = new Candidate_Comment_on_list__c(
            Kandidat_p_liste__c = candidateOnListUIO.Id,
            Name = '63722154444',
            Comment__c = 'Following losses to Nottingham Forest and Manchester City, the black and whites are bidding to avoid a trio of successive PL home defeats for the first time since January/February 2021.',
            Date_added_to_list__c = Date.TODAY()
        );
        insert commentOnListUIO1;

        Candidate_Comment_on_list__c commentOnListUIO2 = new Candidate_Comment_on_list__c(
            Kandidat_p_liste__c = candidateOnListUIO.Id,
            Name = '63722154444',
            Comment__c = 'Following losses to Nottingham Forest and Manchester City, the black and whites are bidding to avoid a trio of successive PL home defeats for the first time since January/February 2021.',
            Date_added_to_list__c = Date.TODAY()
        );
        insert commentOnListUIO2;

        // Instantiate controller with standard controller and test data
        ApexPages.StandardController stdController = new ApexPages.StandardController(candidate);
        TAG_GeneratePdfController controller = new TAG_GeneratePdfController(stdController);

        // Test getCandidateOnList method
        List<Candidate_on_list__c> candidateOnLists = controller.getCandidateOnList(candidate.Id);
        System.assertEquals(2, candidateOnLists.size(), 'Candidate_on_list__c records not retrieved successfully');

        // Test getCommentsOnList method
        List<Candidate_Comment_on_list__c> commentsOnLists = controller.getCommentsOnList();
        System.assertEquals(
            4,
            commentsOnLists.size(),
            'Candidate_Comment_on_list__c records not retrieved successfully'
        );
    }
}